[package]
name = "pil2-proofman-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
deno_core = "0"
deno_ops = "0.206.0"
include_dir = "0.7.4"
tokio = { version = "1", features = ["full"] }
