const fs = require("fs");
const version = require("../package").version;

const setupSnarkCmd = require("./cmd/setup_snark_cmd");

const argv = require("yargs")
    .version(version)
    .usage("node main_setup_snark.js -p <publicsinfo.json> -w <powersoftau.ptau> -t <stdPath> [-n <snark>] [-b <buildDir>]")
    .alias("b", "builddir")
    .alias("t", "stdPath")
    .alias("p", "publicsinfo")
    .alias("w", "ptau")
    .alias("n", "snark")
    .demandOption(["publicsinfo", "ptau", "stdPath", "builddir"])
    .describe("k", "Path to the provingKey directory generated by regular setup")
    .describe("b", "Build directory for output files")
    .describe("t", "Path to PIL2 std library")
    .describe("p", "Path to publics info JSON file")
    .describe("w", "Path to powers of tau file")
    .describe("n", "Final snark type: 'fflonk' or 'plonk' (default: fflonk)")
    .argv;

async function run() {
    if (!argv.builddir) {
        throw new Error("Build directory must be provided");
    }

    const buildDir = argv.builddir;

    if (!argv.publicsinfo) {
        throw new Error("Publics info file must be provided in order to generate final snark");
    }

    if (!argv.ptau) {
        throw new Error("PowersOfTau file must be provided in order to generate final snark");
    }

    if (!argv.stdPath) {
        throw new Error("Std path must be provided");
    }

    if (argv.snark && ["fflonk", "plonk"].indexOf(argv.snark) < 0) {
        throw new Error("Final snark must be 'fflonk' or 'plonk'");
    }

    const publicsInfo = JSON.parse(await fs.promises.readFile(argv.publicsinfo, "utf8"));

    const config = {
        publicsInfo,
        powersOfTauFile: argv.ptau,
        stdPath: argv.stdPath,
        finalSnark: argv.snark || "fflonk",
    };

    await setupSnarkCmd(config, buildDir);

    console.log("Final snark setup files generated correctly");
}

run().then(() => {
    process.exit(0);
}, (err) => {
    console.log(err.message);
    console.log(err.stack);
    process.exit(1);
});
